In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("./sonar_dataset.csv", header=None)
df.sample(5)

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
112,0.0454,0.0472,0.0697,0.1021,0.1397,0.1493,0.1487,0.0771,0.1171,0.1675,...,0.0120,0.0042,0.0238,0.0129,0.0084,0.0218,0.0321,0.0154,0.0053,M
170,0.0134,0.0172,0.0178,0.0363,0.0444,0.0744,0.0800,0.0456,0.0368,0.1250,...,0.0094,0.0048,0.0047,0.0016,0.0008,0.0042,0.0024,0.0027,0.0041,M
17,0.0192,0.0607,0.0378,0.0774,0.1388,0.0809,0.0568,0.0219,0.1037,0.1186,...,0.0331,0.0131,0.0120,0.0108,0.0024,0.0045,0.0037,0.0112,0.0075,R
78,0.0231,0.0351,0.0030,0.0304,0.0339,0.0860,0.1738,0.1351,0.1063,0.0347,...,0.0106,0.0097,0.0022,0.0052,0.0072,0.0056,0.0038,0.0043,0.0030,R
56,0.0152,0.0102,0.0113,0.0263,0.0097,0.0391,0.0857,0.0915,0.0949,0.1504,...,0.0049,0.0041,0.0036,0.0013,0.0046,0.0037,0.0011,0.0034,0.0033,R

In [3]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [4]:
df[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [5]:
X = df.drop(60, axis=1)
y = df[60]
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [6]:
y = pd.get_dummies(y, drop_first=True)
y.sample(5) # R --> 1 and M --> 0

         R
136  False
51    True
80    True
154  False
147  False

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [8]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
67,0.0368,0.0403,0.0317,0.0293,0.0820,0.1342,0.1161,0.0663,0.0155,0.0506,...,0.0058,0.0091,0.0160,0.0160,0.0081,0.0070,0.0135,0.0067,0.0078,0.0068
14,0.0124,0.0433,0.0604,0.0449,0.0597,0.0355,0.0531,0.0343,0.1052,0.2120,...,0.0078,0.0083,0.0057,0.0174,0.0188,0.0054,0.0114,0.0196,0.0147,0.0062
164,0.0163,0.0198,0.0202,0.0386,0.0752,0.1444,0.1487,0.1484,0.2442,0.2822,...,0.0027,0.0077,0.0026,0.0031,0.0083,0.0020,0.0084,0.0108,0.0083,0.0033
179,0.0394,0.0420,0.0446,0.0551,0.0597,0.1416,0.0956,0.0802,0.1618,0.2558,...,0.0118,0.0146,0.0040,0.0114,0.0032,0.0062,0.0101,0.0068,0.0053,0.0087
19,0.0126,0.0149,0.0641,0.1732,0.2565,0.2559,0.2947,0.4110,0.4983,0.5920,...,0.0153,0.0092,0.0035,0.0098,0.0121,0.0006,0.0181,0.0094,0.0116,0.0063

In [9]:
import tensorflow as tf
from tensorflow import keras

2026-05-16 15:43:25.658718: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-05-16 15:43:25.706375: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2026-05-16 15:43:26.114865: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2026-05-16 15:43:26.121485: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-05-16 15:43:29.100598: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 3s 12ms/step - loss: 0.6794 - accuracy: 0.5449
Epoch 2/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6448 - accuracy: 0.7051
Epoch 3/100
20/20 [==============================] - 0s 10ms/step - loss: 0.6195 - accuracy: 0.6859
Epoch 4/100
20/20 [==============================] - 0s 10ms/step - loss: 0.5982 - accuracy: 0.7372
Epoch 5/100
20/20 [==============================] - 0s 7ms/step - loss: 0.5678 - accuracy: 0.7308
Epoch 6/100
20/20 [==============================] - 0s 6ms/step - loss: 0.5420 - accuracy: 0.7179
Epoch 7/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4945 - accuracy: 0.8333
Epoch 8/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4683 - accuracy: 0.8141
Epoch 9/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4304 - accuracy: 0.8526
Epoch 10/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4087 - accuracy: 0.8397
Epoch 11/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3628 - accuracy: 0.8718
Epoch 12/100
20/20 [==============================] - 0s 6ms/step - loss: 0.3896 - accuracy: 0.8269
Epoch 13/100
20/20 [==============================] - 0s 8ms/step - loss: 0.3490 - accuracy: 0.8718
Epoch 14/100
20/20 [==============================] - 0s 12ms/step - loss: 0.3290 - accuracy: 0.8526
Epoch 15/100
20/20 [==============================] - 0s 8ms/step - loss: 0.3055 - accuracy: 0.8718
Epoch 16/100
20/20 [==============================] - 0s 14ms/step - loss: 0.2850 - accuracy: 0.8654
Epoch 17/100
20/20 [==============================] - 0s 10ms/step - loss: 0.2872 - accuracy: 0.8846
Epoch 18/100
20/20 [==============================] - 0s 13ms/step - loss: 0.2448 - accuracy: 0.9103
Epoch 19/100
20/20 [==============================] - 0s 11ms/step - loss: 0.2392 - accuracy: 0.9295
Epoch 20/100
20/20 [==============================] - 0s 8ms/step - loss: 0.2289 - accuracy: 0.9231
Epoch 21/100
20/20 [==============================] - 0s 12ms/step - loss: 0.2207 - accuracy: 0.9103
Epoch 22/100
20/20 [==============================] - 0s 9ms/step - loss: 0.2252 - accuracy: 0.9167
Epoch 23/100
20/20 [==============================] - 0s 9ms/step - loss: 0.2014 - accuracy: 0.9487
Epoch 24/100
20/20 [==============================] - 0s 11ms/step - loss: 0.1778 - accuracy: 0.9487
Epoch 25/100
20/20 [==============================] - 0s 12ms/step - loss: 0.1787 - accuracy: 0.9295
Epoch 26/100
20/20 [==============================] - 0s 11ms/step - loss: 0.1654 - accuracy: 0.9423
Epoch 27/100
20/20 [==============================] - 0s 13ms/step - loss: 0.1606 - accuracy: 0.9615
Epoch 28/100
20/20 [==============================] - 0s 15ms/step - loss: 0.1541 - accuracy: 0.9551
Epoch 29/100
20/20 [==============================] - 0s 11ms/step - loss: 0.1546 - accuracy: 0.9423
Epoch 30/100
20/20 [==============================] - 0s 11ms/step - loss: 0.1358 - accuracy: 0.9615
Epoch 31/100
20/20 [==============================] - 0s 16ms/step - loss: 0.1306 - accuracy: 0.9679
Epoch 32/100
20/20 [==============================] - 0s 9ms/step - loss: 0.1156 - accuracy: 0.9551
Epoch 33/100
20/20 [==============================] - 0s 8ms/step - loss: 0.1079 - accuracy: 0.9744
Epoch 34/100
20/20 [==============================] - 0s 9ms/step - loss: 0.0833 - accuracy: 0.9936
Epoch 35/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0853 - accuracy: 0.9936
Epoch 36/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0762 - accuracy: 0.9872
Epoch 37/100
20/20 [==============================] - 0s 11ms/step - loss: 0.0679 - accuracy: 0.9872
Epoch 38/100
20/20 [==============================] - 0s 9ms/step - loss: 0.0619 - accuracy: 0.9936
Epoch 39/100
20/20 [==============================] - 0s 7ms/step - loss: 0.0536 - accuracy: 0.9936
Epoch 40/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0485 - accuracy: 0.9936
Epoch 41/100
20/20 [==============================] - 0s 6ms/step - loss: 0.0419 - accuracy: 1.0000
Epoch 42/100
20/20 [==============================] - 0s 6ms/step - loss: 0.0441 - accuracy: 0.9936
Epoch 43/100
20/20 [==============================] - 0s 7ms/step - loss: 0.0617 - accuracy: 0.9872
Epoch 44/100
20/20 [==============================] - 0s 6ms/step - loss: 0.0650 - accuracy: 0.9808
Epoch 45/100
20/20 [==============================] - 0s 9ms/step - loss: 0.0470 - accuracy: 0.9936
Epoch 46/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0431 - accuracy: 0.9936
Epoch 47/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0281 - accuracy: 1.0000
Epoch 48/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0233 - accuracy: 1.0000
Epoch 49/100
20/20 [==============================] - 0s 7ms/step - loss: 0.0229 - accuracy: 1.0000
Epoch 50/100
20/20 [==============================] - 0s 7ms/step - loss: 0.0211 - accuracy: 1.0000
Epoch 51/100
20/20 [==============================] - 0s 10ms/step - loss: 0.0225 - accuracy: 1.0000
Epoch 52/100
20/20 [==============================] - 0s 7ms/step - loss: 0.0186 - accuracy: 1.0000
Epoch 53/100
20/20 [==============================] - 0s 7ms/step - loss: 0.0176 - accuracy: 1.0000
Epoch 54/100
20/20 [==============================] - 0s 7ms/step - loss: 0.0139 - accuracy: 1.0000
Epoch 55/100
20/20 [==============================] - 0s 7ms/step - loss: 0.0152 - accuracy: 1.0000
Epoch 56/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0136 - accuracy: 1.0000
Epoch 57/100
20/20 [==============================] - 0s 11ms/step - loss: 0.0123 - accuracy: 1.0000
Epoch 58/100
20/20 [==============================] - 0s 10ms/step - loss: 0.0105 - accuracy: 1.0000
Epoch 59/100
20/20 [==============================] - 0s 12ms/step - loss: 0.0107 - accuracy: 1.0000
Epoch 60/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0091 - accuracy: 1.0000
Epoch 61/100
20/20 [==============================] - 0s 9ms/step - loss: 0.0093 - accuracy: 1.0000
Epoch 62/100
20/20 [==============================] - 0s 7ms/step - loss: 0.0080 - accuracy: 1.0000
Epoch 63/100
20/20 [==============================] - 0s 6ms/step - loss: 0.0076 - accuracy: 1.0000
Epoch 64/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0081 - accuracy: 1.0000
Epoch 65/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0074 - accuracy: 1.0000
Epoch 66/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0067 - accuracy: 1.0000
Epoch 67/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0060 - accuracy: 1.0000
Epoch 68/100
20/20 [==============================] - 0s 13ms/step - loss: 0.0055 - accuracy: 1.0000
Epoch 69/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0056 - accuracy: 1.0000
Epoch 70/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0068 - accuracy: 1.0000
Epoch 71/100
20/20 [==============================] - 0s 11ms/step - loss: 0.0057 - accuracy: 1.0000
Epoch 72/100
20/20 [==============================] - 0s 11ms/step - loss: 0.0051 - accuracy: 1.0000
Epoch 73/100
20/20 [==============================] - 0s 10ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 74/100
20/20 [==============================] - 0s 12ms/step - loss: 0.0041 - accuracy: 1.0000
Epoch 75/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 76/100
20/20 [==============================] - 0s 10ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 77/100
20/20 [==============================] - 0s 9ms/step - loss: 0.0041 - accuracy: 1.0000
Epoch 78/100
20/20 [==============================] - 0s 8ms/step - loss: 0.0033 - accuracy: 1.0000
Epoch 79/100
19/20 [===========================>..] - ETA: 0s - loss: 0.0031 - accuracy: 1.0000

In [ ]:
model.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 1.0993

[1.0992590188980103, 0.75]

In [ ]:
y_pred = model.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
[6.9424985e-08 9.9778974e-01 5.6293011e-01 1.1317915e-05 9.9999821e-01
 9.9976474e-01 7.6143312e-01 9.9999946e-01 1.3250898e-05 9.9999875e-01]
[0. 1. 1. 0. 1. 1. 1. 1. 0. 1.]

In [ ]:
y_test[:10]

         R
186  False
155  False
165  False
200  False
58    True
34    True
151  False
18    True
202  False
62    True

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.73      0.81      0.77        27
        True       0.77      0.68      0.72        25

    accuracy                           0.75        52
   macro avg       0.75      0.75      0.75        52
weighted avg       0.75      0.75      0.75        52

In [ ]:
modeld = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid')
])

modeld.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

modeld.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100

/home/intellect/Documents/Data_Science_Pas2/pasDay_3/tfenv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5064 - loss: 0.7259
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5000 - loss: 0.7399
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5256 - loss: 0.7257
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5449 - loss: 0.6892
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5769 - loss: 0.6859
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4936 - loss: 0.7132
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4679 - loss: 0.6986
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4936 - loss: 0.7021
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5321 - loss: 0.6857
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5962 - loss: 0.6836
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5962 - loss: 0.6754
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5641 - loss: 0.6894
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5449 - loss: 0.6895
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5833 - loss: 0.6809
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5897 - loss: 0.6673
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5513 - loss: 0.6780
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5449 - loss: 0.6842
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5705 - loss: 0.6871
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5641 - loss: 0.6875
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6154 - loss: 0.6848
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5769 - loss: 0.6650
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5641 - loss: 0.6702
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5962 - loss: 0.6711
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6731 - loss: 0.6378
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6154 - loss: 0.6605
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6154 - loss: 0.6409
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5962 - loss: 0.6472
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6090 - loss: 0.6460
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6282 - loss: 0.6522
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6538 - loss: 0.6163
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6154 - loss: 0.6550
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6410 - loss: 0.6273
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6026 - loss: 0.6332
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6731 - loss: 0.5997
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6667 - loss: 0.6043
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6474 - loss: 0.5835
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6923 - loss: 0.5607
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7051 - loss: 0.5768
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7244 - loss: 0.5960
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7244 - loss: 0.5606
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.5199
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7244 - loss: 0.5325
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5252
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7372 - loss: 0.5752
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7692 - loss: 0.5297
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7756 - loss: 0.5195
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7821 - loss: 0.4827
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7244 - loss: 0.5169
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7436 - loss: 0.5502
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8269 - loss: 0.4988
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7564 - loss: 0.4884
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8269 - loss: 0.4751
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7756 - loss: 0.4825
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8462 - loss: 0.4356
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7949 - loss: 0.4600
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8205 - loss: 0.3961
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7821 - loss: 0.4667
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7756 - loss: 0.5183
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8333 - loss: 0.4328
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8269 - loss: 0.4868
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8462 - loss: 0.4200
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8269 - loss: 0.4092
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8526 - loss: 0.3838
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8269 - loss: 0.3920
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8397 - loss: 0.4120
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.3914
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8397 - loss: 0.3934
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4041
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8462 - loss: 0.3912
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8205 - loss: 0.4186
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8974 - loss: 0.3290
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8397 - loss: 0.3628
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8526 - loss: 0.3468
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8590 - loss: 0.3770
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8269 - loss: 0.3949
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8590 - loss: 0.3635
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8397 - loss: 0.3629
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8333 - loss: 0.3655
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8654 - loss: 0.3638
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8974 - loss: 0.3602
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8782 - loss: 0.3192
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8782 - loss: 0.3293
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.3284
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8590 - loss: 0.3371
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8654 - loss: 0.3311
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8782 - loss: 0.2834
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8782 - loss: 0.3154
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9167 - loss: 0.2628
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8974 - loss: 0.2916
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8462 - loss: 0.3428
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8526 - loss: 0.3434
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8974 - loss: 0.3003
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8846 - loss: 0.2914
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8526 - loss: 0.4302
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8846 - loss: 0.3281
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8718 - loss: 0.3327
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8782 - loss: 0.3376
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9103 - loss: 0.2552
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8910 - loss: 0.2948
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8654 - loss: 0.3024

In [ ]:
modeld.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7692 - loss: 0.4655

[0.46550777554512024, 0.7692307829856873]

In [ ]:
y_pred = modeld.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
[0.00248295 0.91850036 0.9191903  0.03841892 0.99984545 0.9140054
 0.52312994 0.9998647  0.04255292 0.9999534 ]
[0. 1. 1. 0. 1. 1. 1. 1. 0. 1.]

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.76      0.81      0.79        27
        True       0.78      0.72      0.75        25

    accuracy                           0.77        52
   macro avg       0.77      0.77      0.77        52
weighted avg       0.77      0.77      0.77        52